openapi: 3.2.0
info:
  title: sample api
  version: 1.0.0

servers:
  - url: "{schema}://{host}:{port}/{path1}/{path2}/v{version}"
    variables:
      schema:
        default: https
        enum:
          - https
          - http
      host:
        default: openapiprocessor.io
      port:
        default: "443"
      path1:
        default: foo
      path2:
        default: bar
      version:
        default: "1"

paths:
  /foo:
    post:
      tags:
        - foo
      summary: echo a Foo.
      description: simple sample endpoint
      requestBody:
          $ref: '#/components/requestBodies/FooBody'
      responses:
        '200':
          description: foo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'

  /bar:
    post:
      tags:
        - bar
      summary: echo a Bar.
      description: simple sample endpoint
      requestBody:
          $ref: '#/components/requestBodies/BarBody'
      responses:
        '200':
          description: bar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bar'

components:
  schemas:
    Foo:
      type: object
      description: Foo object
      properties:
        foo:
          type: string
          maxLength: 10
          description: foo property
        id:
          type: string
          format: uuid
          description: id property
        bar:
          $ref: '#/components/schemas/Bar'
          description: bar property

    Bar:
      type: object
      description: Foo object
      properties:
        bar:
          type: string
          maxLength: 20
          description: bar property

  requestBodies:
    FooBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Foo'

    BarBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Bar'
