= openapi-processor-spring (webflux) sample project
:oap-spring: https://docs.openapiprocessor.io/spring
:oap-json: https://docs.openapiprocessor.io/json
:oap-gradle: https://docs.openapiprocessor.io/gradle
:oap-maven: https://docs.openapiprocessor.io/maven
:oap-github: https://github.com/openapi-processor/openapi-processor-samples/samples/spring-webflux

This is a very simple Spring Boot (gradle & maven) project that is using

* xref:spring::index.adoc[openapi-processor-spring] to generate java interfaces for the api defined in an openapi.yaml file
* xref:json::index.adoc[openapi-processor-json] to convert the openapi yaml to json format
* xref:gradle::index.adoc[openapi-processor-gradle]/xref:maven::index.adoc[openapi-processor-maven] plugin to run both processors

The purpose of the sample is to show the setup of the gradle plugin, and the processors for an **annotation** based Spring WebFlux application.


== Running with gradle

Clone the project from link:{oap-github}[GitHub], navigate into the project root folder `samples/spring-webflux` and run

----
 ../../gradlew bootRun
----

to start the sample application.

== Running with maven

----
../../mvnw spring-boot:run
----

Note that the versions in the `pom.xml` are probably not up to date.

== Sample Endpoints

the sample has a few simple endpoints described with OpenAPI in `src/api`.

=== get all books

    curl http://localhost:8080/books

=== get single book

    curl http://localhost:8080/books/1

=== post new books

    curl --header "Content-Type: application/json" --data '[{"title":"Test Driven Development","authors":["Kent Beck"]}, {"title":"Growing Object-Oriented Software","authors":["Steve Freeman", "Nat Pryce"]}]' http://localhost:8080/books

