openapi: 3.2.0
$self: '../main/kotlin/io/openapiprocessor/samples/'
info:
  title: openapi-processor-spring stream sample api
  version: 1.0.0

servers:
  - url: "https://openapiprocessor.io/{path}"
    variables:
      path:
        default: api

paths:
  /sse:
    $ref: 'sse/sse.yaml'

  /jsonl:
    $ref: 'jsonl/jsonl.yaml'
