openapi: 3.1.0
info:
  title: openapi-processor-spring sample api
  version: 1.0.0

paths:
  /api2/foo:
    post:
      summary: api with enum in body and parameter.
      parameters:
        - name: type
          description: enum parameter
          in: query
          schema:
            $ref: '#/components/schemas/Type'

      requestBody:
          $ref: '#/components/requestBodies/FooBody'
      responses:
        '200':
          description: foo response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'

components:
  schemas:
    Foo:
      type: object
      description: Foo
      properties:
        id:
          type: string
          format: uuid
          description: an id
        type:
          $ref: '#/components/schemas/Type'
          description: an enum

    Type:
      type: string
      description: Type
      enum:
        - foo
        - bar

  requestBodies:
   FooBody:
     content:
       application/json:
         schema:
           $ref: '#/components/schemas/Foo'
