openapi: 3.0.3
info:
  title: openapi-processor-spring sample api
  version: 1.0.0

paths:

  /books:
    get:
      tags:
        - book
      description: returns all known books
      responses:
        '200':
          description: list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

    post:
      tags:
        - book
      description: updates the list of available books. Does not check for duplicate books.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: success

  /books/{id}:
    get:
      tags:
        - book
      description: get the book with the given {id}
      parameters:
        - name: id
          in: path
          description: ID of the book
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: a single book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'


components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        authors:
          type: array
          items:
            type: string
